import { useEffect, useMemo, useState } from "react";
import {
  LanguageContext,
  SupportedLanguage,
  LanguageContextValue,
} from "@/context/language-store";

type TranslationMap = Record<string, string>;

const STORAGE_KEY = "urbansight_language";

const en: TranslationMap = {
  "common.profile": "Profile",
  "common.settings": "Settings",
  "common.notifications": "Notifications",
  "common.system": "System",
  "common.logout": "Log out",
  "common.user": "User",
  "common.search.placeholder": "Search requests, tasks, users...",
  "common.notifications.empty": "No notifications",
  "common.system.notification": "System Notification",
  "common.signedOut": "Signed out",
  "common.logoutFailed": "Logout failed",
  "common.tryAgain": "Try again",
  "common.success": "Success",
  "common.ok": "OK",
  "common.language": "Language",
  "common.english": "English",
  "common.amharic": "Amharic",
  "nav.dashboard": "Dashboard",
  "nav.myRequests": "My Requests",
  "nav.newConnection": "New Connection",
  "nav.reportIssue": "Report Issue",
  "nav.serviceRequests": "Service Requests",
  "nav.issueReports": "Issue Reports",
  "nav.inspection": "Inspection",
  "nav.payments": "Payments",
  "nav.usersRoles": "Users & Roles",
  "nav.collapse": "Collapse",
  "role.citizen": "Citizen",
  "role.director": "Customer Service Director",
  "role.coordinator": "Branch Coordinator",
  "role.surveyor": "Surveyor",
  "role.technician": "Technician",
  "role.meter_reader": "Meter Reader",
  "role.finance": "Finance Officer",
  "role.admin": "System Admin",
  "settings.title": "Settings",
  "settings.subtitle": "Manage your account and preferences",
  "settings.profile.save": "Save Profile",
  "settings.profile.saving": "Saving...",
  "settings.password.change": "Change Password",
  "settings.password.current": "Current Password",
  "settings.password.new": "New Password",
  "settings.password.confirm": "Confirm Password",
  "settings.password.update": "Update Password",
  "settings.password.updating": "Updating...",
  "settings.system.multiLanguage": "Multi-language support",
  "settings.system.multiLanguageDesc":
    "Choose your preferred interface language",
  "auth.title": "UrbanSight Access",
  "auth.signIn": "Sign in",
  "auth.createAccount": "Create account",
  "auth.login": "Login",
  "auth.register": "Register",
  "auth.staffLogin": "Staff Login",
  "auth.workEmail": "Work email",
  "auth.password": "Password",
  "auth.rememberMe": "Remember me",
  "auth.forgotPassword": "Forgot password?",
  "auth.signInButton": "Sign in to UrbanSight",
  "auth.fullName": "Full name",
  "auth.email": "Email",
  "auth.phoneEthiopia": "Phone (Ethiopia)",
  "auth.confirmPassword": "Confirm password",
  "auth.createCitizenAccount": "Create citizen account",
  "auth.orContinueWith": "or continue with",
  "form.customerName": "Customer Name",
  "form.customerNameAmharic": "Customer Name (Amharic)",
  "form.tinNumber": "TIN Number",
  "form.phoneNumber": "Phone Number",
  "form.familyMembers": "Number of Family Members",
  "form.address": "Address",
  "form.houseZone": "House Number / Zone",
  "form.readingZone": "Reading Zone",
  "form.meterSize": "Meter Size",
  "form.customerGroup": "Customer Group",
  "form.connectionType": "Connection Type",
  "form.serviceType": "Service Type",
  "form.selectBranch": "Select Branch",
  "form.descriptionOptional": "Description (optional)",
  "form.housePlanRequired": "House Plan (required)",
  "form.idCardRequired": "ID Card (required)",
  "form.additionalAttachments": "Additional Attachments (optional)",
  "form.uploading": "Uploading...",
  "form.uploadingAttachments": "Uploading attachments...",
  "form.attachmentsUploaded": "attachment(s) uploaded",
  "form.submitting": "Submitting...",
  "form.submitRequest": "Submit Request",
  "citizen.newConnection.title": "New Water Connection",
  "citizen.newConnection.subtitle": "Submit a new connection request",
  "citizen.payment.title": "Proceed to Payment",
  "citizen.payment.subtitle": "Complete payment for required tools/materials",
  "citizen.payment.summary": "Request Summary",
  "citizen.payment.requiredTools": "Required Tools / Materials",
  "citizen.payment.totalEstimated": "Total Estimated Cost",
  "citizen.payment.submission": "Payment Submission",
  "citizen.payment.transactionId": "Transaction ID",
  "citizen.payment.method": "Payment Method",
  "citizen.payment.selectMethod": "Select payment method",
  "citizen.payment.receipt": "Receipt Upload (Image/PDF)",
  "citizen.payment.submit": "Submit Payment",
  "citizen.reportIssue.title": "Report an Issue",
  "citizen.reportIssue.subtitle":
    "Submit a water service issue and the utility team will review it.",
  "citizen.reportIssue.prevInfo": "Previous Submitted Connection Information",
  "citizen.reportIssue.completedConnection": "Completed Water Connection",
  "citizen.reportIssue.selectConnection": "Select connection",
  "citizen.reportIssue.issueSubmission": "Issue Submission",
  "citizen.reportIssue.type": "Type of Issue",
  "citizen.reportIssue.attachment": "Issue Attachment Document",
  "citizen.reportIssue.submit": "Submit Issue",
  "citizen.reportIssue.uploadOne":
    "Upload one supporting document before submit.",
  "citizen.reportIssue.uploadingAttachment": "Uploading attachment...",
  "citizen.reportIssue.viewAttachment": "View uploaded issue attachment",
  "citizen.reportIssue.customerCode": "Customer Code",
  "citizen.reportIssue.connectionCode": "Water Connection Code",
  "citizen.reportIssue.locationReadonly": "Submitted Location (Read Only)",
  "citizen.reportIssue.docsReadonly": "Submitted Documents (Read Only)",
  "citizen.reportIssue.noCompleted": "No completed connections available",
  "citizen.reportIssue.selectToView":
    "Select a completed connection to view all previously submitted details.",
  "common.loading": "Loading...",
  "common.email": "Email",
  "common.branch": "Branch",
  "common.customer": "Customer",
  "common.status": "Status",
  "common.requestId": "Request ID",
  "common.code": "Code",
  "common.description": "Description",
  "common.quantity": "Quantity",
  "common.unitPrice": "Unit Price",
  "common.totalPrice": "Total Price",
  "issue.billing": "Billing Issue",
  "issue.leakage": "Leakage",
  "issue.meterFault": "Meter Fault",
  "issue.noSupply": "No Water Supply",
  "issue.quality": "Water Quality",
  "issue.other": "Other",
};

const am: TranslationMap = {
  "common.profile": "መገለጫ",
  "common.settings": "ቅንብሮች",
  "common.notifications": "ማሳወቂያዎች",
  "common.system": "ሲስተም",
  "common.logout": "ውጣ",
  "common.user": "ተጠቃሚ",
  "common.search.placeholder": "ጥያቄዎች፣ ተግባራት፣ ተጠቃሚዎች ፈልግ...",
  "common.notifications.empty": "ማሳወቂያ የለም",
  "common.system.notification": "የሲስተም ማሳወቂያ",
  "common.signedOut": "ወጥተዋል",
  "common.logoutFailed": "መውጣት አልተሳካም",
  "common.tryAgain": "እንደገና ይሞክሩ",
  "common.success": "ተሳክቷል",
  "common.ok": "እሺ",
  "common.language": "ቋንቋ",
  "common.english": "እንግሊዝኛ",
  "common.amharic": "አማርኛ",
  "nav.dashboard": "ዳሽቦርድ",
  "nav.myRequests": "የእኔ ጥያቄዎች",
  "nav.newConnection": "አዲስ ግንኙነት",
  "nav.reportIssue": "ችግር ሪፖርት",
  "nav.serviceRequests": "የአገልግሎት ጥያቄዎች",
  "nav.issueReports": "የችግር ሪፖርቶች",
  "nav.inspection": "ምርመራ",
  "nav.payments": "ክፍያዎች",
  "nav.usersRoles": "ተጠቃሚዎች እና ሚናዎች",
  "nav.collapse": "አጥር",
  "role.citizen": "ዜጋ",
  "role.director": "የአገልግሎት ዳይሬክተር",
  "role.coordinator": "የቅርንጫፍ ኮርዲኔተር",
  "role.surveyor": "ሰርቬየር",
  "role.technician": "ቴክኒሺያን",
  "role.meter_reader": "ሜትር አንባቢ",
  "role.finance": "የፋይናንስ ባለሙያ",
  "role.admin": "ሲስተም አስተዳዳሪ",
  "settings.title": "ቅንብሮች",
  "settings.subtitle": "መለያዎን እና ምርጫዎችዎን ያስተዳድሩ",
  "settings.profile.save": "መገለጫ አስቀምጥ",
  "settings.profile.saving": "በማስቀመጥ ላይ...",
  "settings.password.change": "የይለፍ ቃል ቀይር",
  "settings.password.current": "የአሁኑ የይለፍ ቃል",
  "settings.password.new": "አዲስ የይለፍ ቃል",
  "settings.password.confirm": "የይለፍ ቃል አረጋግጥ",
  "settings.password.update": "የይለፍ ቃል አዘምን",
  "settings.password.updating": "በማዘመን ላይ...",
  "settings.system.multiLanguage": "ባለብዙ ቋንቋ ድጋፍ",
  "settings.system.multiLanguageDesc": "የሚመርጡትን የበይነገጽ ቋንቋ ይምረጡ",
  "auth.title": "የUrbanSight መግቢያ",
  "auth.signIn": "ግባ",
  "auth.createAccount": "መለያ ፍጠር",
  "auth.login": "ግባ",
  "auth.register": "ተመዝገብ",
  "auth.staffLogin": "የሰራተኛ መግቢያ",
  "auth.workEmail": "የስራ ኢሜይል",
  "auth.password": "የይለፍ ቃል",
  "auth.rememberMe": "አስታውሰኝ",
  "auth.forgotPassword": "የይለፍ ቃል ረሱ?",
  "auth.signInButton": "ወደ UrbanSight ግባ",
  "auth.fullName": "ሙሉ ስም",
  "auth.email": "ኢሜይል",
  "auth.phoneEthiopia": "ስልክ (ኢትዮጵያ)",
  "auth.confirmPassword": "የይለፍ ቃል አረጋግጥ",
  "auth.createCitizenAccount": "የዜጋ መለያ ፍጠር",
  "auth.orContinueWith": "ወይም በሚከተለው ይቀጥሉ",
  "form.customerName": "የደንበኛ ስም",
  "form.customerNameAmharic": "የደንበኛ ስም (በአማርኛ)",
  "form.tinNumber": "TIN ቁጥር",
  "form.phoneNumber": "ስልክ ቁጥር",
  "form.familyMembers": "የቤተሰብ አባላት ብዛት",
  "form.address": "አድራሻ",
  "form.houseZone": "የቤት ቁጥር / ዞን",
  "form.readingZone": "የንባብ ዞን",
  "form.meterSize": "የሜትር መጠን",
  "form.customerGroup": "የደንበኛ ቡድን",
  "form.connectionType": "የግንኙነት አይነት",
  "form.serviceType": "የአገልግሎት አይነት",
  "form.selectBranch": "ቅርንጫፍ ይምረጡ",
  "form.descriptionOptional": "መግለጫ (አማራጭ)",
  "form.housePlanRequired": "የቤት ፕላን (አስፈላጊ)",
  "form.idCardRequired": "መታወቂያ ካርድ (አስፈላጊ)",
  "form.additionalAttachments": "ተጨማሪ አባሪዎች (አማራጭ)",
  "form.uploading": "በመጫን ላይ...",
  "form.uploadingAttachments": "አባሪዎች በመጫን ላይ...",
  "form.attachmentsUploaded": "አባሪ ተጭኗል",
  "form.submitting": "በማቅረብ ላይ...",
  "form.submitRequest": "ጥያቄ አቅርብ",
  "citizen.newConnection.title": "አዲስ የውሃ ግንኙነት",
  "citizen.newConnection.subtitle": "አዲስ የግንኙነት ጥያቄ ያቅርቡ",
  "citizen.payment.title": "ወደ ክፍያ ይቀጥሉ",
  "citizen.payment.subtitle": "ለሚያስፈልጉ መሳሪያዎች/እቃዎች ክፍያን ያጠናቁ",
  "citizen.payment.summary": "የጥያቄ ማጠቃለያ",
  "citizen.payment.requiredTools": "የሚያስፈልጉ መሳሪያዎች / እቃዎች",
  "citizen.payment.totalEstimated": "ጠቅላላ የተገመተ ወጪ",
  "citizen.payment.submission": "የክፍያ ማቅረቢያ",
  "citizen.payment.transactionId": "የግብይት መለያ",
  "citizen.payment.method": "የክፍያ ዘዴ",
  "citizen.payment.selectMethod": "የክፍያ ዘዴ ይምረጡ",
  "citizen.payment.receipt": "ደረሰኝ አስገባ (ምስል/PDF)",
  "citizen.payment.submit": "ክፍያ አቅርብ",
  "citizen.reportIssue.title": "ችግር ሪፖርት አቅርብ",
  "citizen.reportIssue.subtitle": "የውሃ አገልግሎት ችግር ያቅርቡ እና ቡድኑ ይገምግማል።",
  "citizen.reportIssue.prevInfo": "ቀድሞ የቀረበ የግንኙነት መረጃ",
  "citizen.reportIssue.completedConnection": "የተጠናቀቀ የውሃ ግንኙነት",
  "citizen.reportIssue.selectConnection": "ግንኙነት ይምረጡ",
  "citizen.reportIssue.issueSubmission": "የችግር ማቅረቢያ",
  "citizen.reportIssue.type": "የችግር አይነት",
  "citizen.reportIssue.attachment": "የችግር አባሪ ሰነድ",
  "citizen.reportIssue.submit": "ችግር አቅርብ",
  "citizen.reportIssue.uploadOne": "ከማቅረብ በፊት አንድ የድጋፍ ሰነድ ያስገቡ።",
  "citizen.reportIssue.uploadingAttachment": "አባሪ በመጫን ላይ...",
  "citizen.reportIssue.viewAttachment": "የተጫነውን አባሪ ይመልከቱ",
  "citizen.reportIssue.customerCode": "የደንበኛ ኮድ",
  "citizen.reportIssue.connectionCode": "የውሃ ግንኙነት ኮድ",
  "citizen.reportIssue.locationReadonly": "የቀረበ አካባቢ (ለማንበብ ብቻ)",
  "citizen.reportIssue.docsReadonly": "የቀረቡ ሰነዶች (ለማንበብ ብቻ)",
  "citizen.reportIssue.noCompleted": "የተጠናቀቁ ግንኙነቶች የሉም",
  "citizen.reportIssue.selectToView":
    "ሁሉንም ቀድሞ የቀረበ ዝርዝሮች ለማየት የተጠናቀቀ ግንኙነት ይምረጡ።",
  "common.loading": "በመጫን ላይ...",
  "common.email": "ኢሜይል",
  "common.branch": "ቅርንጫፍ",
  "common.customer": "ደንበኛ",
  "common.status": "ሁኔታ",
  "common.requestId": "የጥያቄ መለያ",
  "common.code": "ኮድ",
  "common.description": "መግለጫ",
  "common.quantity": "ብዛት",
  "common.unitPrice": "የአንዱ ዋጋ",
  "common.totalPrice": "ጠቅላላ ዋጋ",
  "issue.billing": "የክፍያ ችግር",
  "issue.leakage": "ፍሳሽ",
  "issue.meterFault": "የሜትር ችግር",
  "issue.noSupply": "የውሃ አቅርቦት የለም",
  "issue.quality": "የውሃ ጥራት",
  "issue.other": "ሌላ",
};

const dictionaries: Record<SupportedLanguage, TranslationMap> = { en, am };

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>("en");

  useEffect(() => {
    if (typeof window === "undefined") return;

    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored === "en" || stored === "am") {
      setLanguageState(stored);
    }
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;

    document.documentElement.lang = language === "am" ? "am" : "en";
  }, [language]);

  const setLanguage = (next: SupportedLanguage) => {
    setLanguageState(next);

    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, next);
    }
  };

  const value = useMemo<LanguageContextValue>(() => {
    const dictionary = dictionaries[language];
    return {
      language,
      setLanguage,
      locale: language === "am" ? "am-ET" : "en-US",
      t: (key, fallback) => dictionary[key] || fallback || key,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
